[workspace]
resolver = "2"
members = [
    "d*",
    "aoc"
]

[workspace.dependencies]
regex = "1.10.1"
log = "0.4.20"
env_logger = "0.10.1"
rayon = "1.8.0"
indicatif = { version = "0.17.7", features = ["rayon"] }